### ISSUE TITLE
ReturnTo parameter in Mellon redirect is double URL encoded

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-it/nubis-securitywiki#12]
**Issue example:**

https://www.securitywiki-stage.stage.us-west-2.appsvcs-securitywiki.nubis.allizom.org/mellon/login?ReturnTo=http%253A%252F%252Fwww.securitywiki%252Dstage.stage.us%252Dwest%252D2.appsvcs%252Dsecuritywiki.nubis.allizom.org%252F%25251B%255B0m&IdP=http%253A%252F%252Fwww.okta.com%252F[removed Okta stuff]

When something like this is seen, the 500 is returned by Apache:

```
http%253A%252F%252F
```

**An overview of what is happening:**

1. User requests https://www.securitywiki-stage.stage.us-west-2.appsvcs-securitywiki.nubis.allizom.org/
2. User is not authenticated so they are redirected to http://www.securitywiki-stage.stage.us-west-2.appsvcs-securitywiki.nubis.allizom.org/mellon/login?ReturnTo=http://www.securitywiki-stage.stage.us-west-2.appsvcs-securitywiki.nubis.allizom.org/&IdP=http://www.okta.com/[removed Okta stuff]
3. This should take them to the `/mellon/login` endpoint with a `ReturnTo` parameter defined as the server we want to come back to after authentication. I believe that this is extracted from the `ServerName` parameter in the Apache configuration. **Notice that it is prefixed with HTTP**
4. The HTTP request is redirected to HTTPS per our Apache configuration
5. This seems to be resulting in a double URL encoded `ReturnTo` parameter and we receive a 500 before being directed to our identity provider

You can manually fix this by manually fixing the double encoding and submitting a request like the issue example above.

**Proposed solution:**

You can fix this by changing the ServerName parameter in the Apache configuration to be:
https://www.securitywiki-stage.stage.us-west-2.appsvcs-securitywiki.nubis.allizom.org

When we perform the DNS change for SecurityWiki, we'd have to change it again to match what users are requesting. I'm not sure if a better solution exists here.

**Comment by gozer** [comment]
Main problem here is keeping in mind the same AMI is used for both stage and prod, so you can't hard-code things like servername in the image, ever.

This is a bug in mod_auth_mellon, AFAICT, because, normally, if there is no specific ServerName set, apache should construct the canonical from the Host header, unless UseCanonicalName is On, which it isn't by default.

If this is a limitation of mod_auth_mellon, I'd suggest simply generating the servername from the environment, unfortunately.

Once mozilla-it/nubis-securitywiki#14 lands, you'll get config/ENVIRONMENT in Consul, so you could very easily use that to construct the correct hostname then use something like

```
Include /etc/apache/hostname.conf
```

**Comment by gozer** [comment]
But generally, it's really silly/bad for http things to need to know their own URLs and can't compute it themselves from client-supplied information, but can't help it.

**Comment by danielhartnell** [comment]
After reviewing the `facter` output, I found that `NUBIS_ENVIRONMENT` provides our environment. With this, we can simplify and use Puppet instead of Consul. Any thoughts regarding this implementation?

```
if $facts['NUBIS_ENVIRONMENT'] == 'stage' {
    $servername = 'https://phonebook.allizom.org'
}
else {
    $servername = 'https://phonebook.mozilla.org'
}

apache::vhost { $project_name:
    servername     => $servername,
    serveradmin    => 'webops@mozilla.com',
...
```

**Comment by danielhartnell** [comment]
Slight adjustment: `NUBIS_ENVIRONMENT` is part of a string in another fact. We can still use regular expressions to check if we are in prod or stage.

**Comment by gozer** [comment]
Nope, puppet runs at image build time, won't work.

For anything that changes between deployments, you have to rely on runtime information.

**Comment by ziegeer** [comment]
Fixed with an apache include and a confd template.
